### ISSUE TITLE
Review of menu names - ja

### ISSUE THREAD

**Issue by dpshelio** [swcarpentry-i18n/carp-theme#2]
[`assets/i18n/ja.md`](https://github.com/swcarpentry-i18n/carp-theme/blob/master/assets/i18n/ja.md) needs to be reviewed as noted on #1.

**Comment by TomKellyGenetics** [comment]
This should be addressed by PR #7. As discussed https://github.com/swcarpentry-ja/i18n/pull/114 and https://github.com/swcarpentry-ja/i18n/pull/118 these have all been reviewed by native Japanese speakers.
